# Generated by Django 5.1.2 on 2024-11-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_categorie', models.CharField(max_length=100)),
                ('descriere_categorie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comenzii', models.DateTimeField(auto_now_add=True)),
                ('status_comanda', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_furnizor', models.CharField(max_length=100)),
                ('adresa_furnizor', models.TextField()),
                ('telefon_furnizor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_produs', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comentariu', models.TextField()),
                ('data_evaluarii', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produs')),
            ],
        ),
        migrations.CreateModel(
            name='ComandaProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField()),
                ('pret_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Stoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField()),
                ('data_actualizarii', models.DateTimeField(auto_now=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produs')),
            ],
        ),
    ]
