# Generated by Django 5.1.2 on 2024-12-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_vizualizare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField(verbose_name='Data expirării')),
                ('subiect', models.CharField(max_length=255)),
                ('procent_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categorii', models.ManyToManyField(to='ecommerce.categorie')),
            ],
        ),
    ]
