# Generated by Django 5.1.2 on 2024-12-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_promotie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza oferta reducere 50%')]},
        ),
    ]
